//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherKitHelper.Tests.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherKitHelper.Tests.Model.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;logoDark@3x&quot;:&quot;/assets/branding/ru/Apple_Weather_wht_ru_3X_090122.png&quot;,&quot;logoLight@1x&quot;:&quot;/assets/branding/ru/Apple_Weather_blk_ru_1X_090122.png&quot;,&quot;logoDark@2x&quot;:&quot;/assets/branding/ru/Apple_Weather_wht_ru_2X_090122.png&quot;,&quot;logoDark@1x&quot;:&quot;/assets/branding/ru/Apple_Weather_wht_ru_1X_090122.png&quot;,&quot;logoLight@2x&quot;:&quot;/assets/branding/ru/Apple_Weather_blk_ru_2X_090122.png&quot;,&quot;logoLight@3x&quot;:&quot;/assets/branding/ru/Apple_Weather_blk_ru_3X_090122.png&quot;,&quot;logoSquare@2x&quot;:&quot;/assets/branding/square-mark@2x.png&quot;,&quot;serviceName&quot;:&quot;Apple Weather [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AttributionResponse {
            get {
                return ResourceManager.GetString("AttributionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;currentWeather&quot;:{&quot;name&quot;:&quot;CurrentWeather&quot;,&quot;metadata&quot;:{&quot;attributionURL&quot;:&quot;https://developer.apple.com/weatherkit/data-source-attribution/&quot;,&quot;expireTime&quot;:&quot;2025-08-13T10:46:01Z&quot;,&quot;latitude&quot;:41.910,&quot;longitude&quot;:12.450,&quot;readTime&quot;:&quot;2025-08-13T10:41:01Z&quot;,&quot;reportedTime&quot;:&quot;2025-08-13T10:41:01Z&quot;,&quot;units&quot;:&quot;m&quot;,&quot;version&quot;:1,&quot;sourceType&quot;:&quot;modeled&quot;},&quot;asOf&quot;:&quot;2025-08-13T10:41:01Z&quot;,&quot;cloudCover&quot;:0.24,&quot;cloudCoverLowAltPct&quot;:0.01,&quot;cloudCoverMidAltPct&quot;:0.05,&quot;cloudCoverHighAltPct&quot;:0.29,&quot;conditionCode&quot;:&quot;MostlyClear&quot;,&quot;daylight&quot;:true,&quot;humi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CurrentWeatherResponse {
            get {
                return ResourceManager.GetString("CurrentWeatherResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;forecastDaily&quot;:{&quot;name&quot;:&quot;DailyForecast&quot;,&quot;metadata&quot;:{&quot;attributionURL&quot;:&quot;https://developer.apple.com/weatherkit/data-source-attribution/&quot;,&quot;expireTime&quot;:&quot;2025-08-13T11:38:00Z&quot;,&quot;latitude&quot;:41.910,&quot;longitude&quot;:12.450,&quot;readTime&quot;:&quot;2025-08-13T10:38:00Z&quot;,&quot;reportedTime&quot;:&quot;2025-08-13T09:05:35Z&quot;,&quot;units&quot;:&quot;m&quot;,&quot;version&quot;:1,&quot;sourceType&quot;:&quot;modeled&quot;},&quot;days&quot;:[{&quot;forecastStart&quot;:&quot;2025-08-12T22:00:00Z&quot;,&quot;forecastEnd&quot;:&quot;2025-08-13T22:00:00Z&quot;,&quot;conditionCode&quot;:&quot;MostlyClear&quot;,&quot;maxUvIndex&quot;:8,&quot;moonPhase&quot;:&quot;waningGibbous&quot;,&quot;moonrise&quot;:&quot;2025-08-13T20 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForecastDailyResponse {
            get {
                return ResourceManager.GetString("ForecastDailyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;forecastHourly&quot;:{&quot;name&quot;:&quot;HourlyForecast&quot;,&quot;metadata&quot;:{&quot;attributionURL&quot;:&quot;https://developer.apple.com/weatherkit/data-source-attribution/&quot;,&quot;expireTime&quot;:&quot;2025-08-13T12:13:41Z&quot;,&quot;latitude&quot;:41.910,&quot;longitude&quot;:12.450,&quot;readTime&quot;:&quot;2025-08-13T11:13:41Z&quot;,&quot;reportedTime&quot;:&quot;2025-08-13T09:05:35Z&quot;,&quot;units&quot;:&quot;m&quot;,&quot;version&quot;:1,&quot;sourceType&quot;:&quot;modeled&quot;},&quot;hours&quot;:[{&quot;forecastStart&quot;:&quot;2025-08-13T11:00:00Z&quot;,&quot;cloudCover&quot;:0.21,&quot;conditionCode&quot;:&quot;MostlyClear&quot;,&quot;daylight&quot;:true,&quot;humidity&quot;:0.33,&quot;precipitationAmount&quot;:0.0,&quot;precipitationIntensity&quot;:0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForecastHourlyResponse {
            get {
                return ResourceManager.GetString("ForecastHourlyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;forecastNextHour&quot;:{&quot;name&quot;:&quot;NextHourForecast&quot;,&quot;metadata&quot;:{&quot;attributionURL&quot;:&quot;https://developer.apple.com/weatherkit/data-source-attribution/&quot;,&quot;expireTime&quot;:&quot;2025-08-13T12:21:08Z&quot;,&quot;latitude&quot;:38.895,&quot;longitude&quot;:-77.036,&quot;providerName&quot;:&quot;US National Oceanic &amp; Atmospheric Administration&quot;,&quot;readTime&quot;:&quot;2025-08-13T11:21:08Z&quot;,&quot;reportedTime&quot;:&quot;2025-08-13T11:14:00Z&quot;,&quot;units&quot;:&quot;m&quot;,&quot;version&quot;:1,&quot;sourceType&quot;:&quot;modeled&quot;},&quot;summary&quot;:[{&quot;startTime&quot;:&quot;2025-08-13T11:21:00Z&quot;,&quot;condition&quot;:&quot;clear&quot;,&quot;precipitationChance&quot;:0.01,&quot;precipitationIn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForecastNextHourResponse {
            get {
                return ResourceManager.GetString("ForecastNextHourResponse", resourceCulture);
            }
        }
    }
}
